-- Add all artisan categories (57 total)
INSERT INTO categories (slug, name) VALUES 
('bricklayer','Bricklayer / Mason'),
('carpenter','Carpenter'),
('plumber','Plumber'),
('electrician','Electrician'),
('welder','Welder'),
('painter','Painter'),
('tiler','Tiler'),
('roofer','Roofer'),
('concrete_worker','Concrete Worker'),
('draughtsman','Draughtsman / Survey Assistant'),
('architect','Architect'),
('engineer','Engineer'),
('interior_designer','Interior Designer'),
('landscape_designer','Landscape Designer'),
('car_mechanic','Car Mechanic'),
('motorcycle_repairer','Motorcycle Repairer'),
('truck_mechanic','Truck / Heavy Duty Mechanic'),
('panel_beater','Panel Beater'),
('spray_painter','Spray Painter'),
('vulcanizer','Vulcanizer (Tyre Repair)'),
('auto_electrician','Auto Electrician'),
('diesel_mechanic','Diesel Mechanic'),
('generator_mechanic','Generator Mechanic'),
('tailor','Tailor / Fashion Designer'),
('shoemaker','Shoemaker / Leather Worker'),
('barber','Barber'),
('hair_stylist','Hair Stylist'),
('makeup_artist','Makeup Artist'),
('spa_therapist','Spa / Massage Therapist'),
('bead_maker','Bead Maker / Jewelry Artisan'),
('caterer','Caterer'),
('baker','Baker'),
('chef','Chef'),
('event_planner','Event Planner'),
('photographer','Photographer'),
('videographer','Videographer'),
('housekeeper','Housekeeper'),
('nanny','Nanny / Babysitter'),
('gardener','Gardener'),
('laundry_worker','Laundry Worker'),
('dry_cleaner','Dry Cleaner'),
('pest_control','Pest Control / Fumigation Specialist'),
('cleaner','Cleaner'),
('driver','Driver'),
('security_guard','Security Guard'),
('ac_repairer','Refrigeration / AC Repairer'),
('electronics_technician','Electronics Technician'),
('computer_repairer','Computer Repairer'),
('phone_technician','Phone Technician'),
('solar_installer','Solar Panel Installer'),
('cctv_installer','CCTV Installer'),
('network_technician','Network Technician'),
('uplogger','Upholsterer'),
('glass_fitter','Glass Fitter'),
('window_fitter','Window Fitter'),
('blinds_fitter','Blinds Fitter'),
('curtain_fitter','Curtain Fitter'),
('marble_installer','Marble Installer'),
('granite_installer','Granite Installer'),
('water_proofer','Water Proofing Specialist'),
('insulation_specialist','Insulation Specialist')
ON CONFLICT (slug) DO NOTHING;
