// Complete list of Nigerian states and their major cities
const Map<String, List<String>> nigeriaStatesAndCities = {
  'Abia': ['Umuahia', 'Aba', 'Ohafia', 'Bende', 'Arochukwu'],
  'Adamawa': ['Yola', 'Mubi', 'Jimeta', 'Numan', 'Ganye'],
  'Akwa Ibom': ['Uyo', 'Ikot Ekpene', 'Eket', 'Oron', 'Abak'],
  'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ihiala', 'Agulu'],
  'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Toro', 'Jama’are'],
  'Bayelsa': ['Yenagoa', 'Ogbia', 'Brass', 'Sagbama', 'Nembe'],
  'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya'],
  'Borno': ['Maiduguri', 'Biu', 'Monguno', 'Chibok', 'Gwoza'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu', 'Akamkpa'],
  'Delta': ['Asaba', 'Warri', 'Ughelli', 'Sapele', 'Agbor'],
  'Ebonyi': ['Abakaliki', 'Afikpo', 'Ikwo', 'Onueke', 'Ezza'],
  'Edo': ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Irrua'],
  'Ekiti': ['Ado-Ekiti', 'Ikere-Ekiti', 'Ijero', 'Omuo', 'Aramoko'],
  'Enugu': ['Enugu', 'Nsukka', 'Agbani', 'Udi', 'Oji River'],
  'FCT (Abuja)': ['Abuja city', 'Gwagwalada', 'Kuje', 'Bwari', 'Nyanya'],
  'Gombe': ['Gombe', 'Kaltungo', 'Dukku', 'Billiri', 'Bajoga'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta'],
  'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Kazaure', 'Birnin Kudu'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Soba', 'Birnin Gwari'],
  'Kano': ['Kano', 'Wudil', 'Rano', 'Gwarzo', 'Madobi'],
  'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma'],
  'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega'],
  'Kogi': ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa'],
  'Kwara': ['Ilorin', 'Offa', 'Jebba', 'Omu-Aran', 'Patigi'],
  'Lagos': ['Ikeja', 'Ikorodu', 'Epe', 'Badagry', 'Victoria Island', 'Surulere', 'Apapa'],
  'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Karu', 'Doma'],
  'Niger': ['Minna', 'Bida', 'Kontagora', 'Suleja', 'Mokwa'],
  'Ogun': ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ota', 'Ilaro'],
  'Ondo': ['Akure', 'Owo', 'Ondo', 'Ikare', 'Idanre'],
  'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Ikirun'],
  'Oyo': ['Ibadan', 'Ogbomoso', 'Oyo', 'Saki', 'Iseyin'],
  'Plateau': ['Jos', 'Pankshin', 'Shendam', 'Barkin Ladi', 'Langtang'],
  'Rivers': ['Port Harcourt', 'Bonny', 'Omoku', 'Bori', 'Ahoada'],
  'Sokoto': ['Sokoto', 'Tambuwal', 'Wurno', 'Gwadabawa', 'Illela'],
  'Taraba': ['Jalingo', 'Wukari', 'Serti', 'Bali', 'Takum'],
  'Yobe': ['Damaturu', 'Potiskum', 'Nguru', 'Gashua', 'Geidam'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Maru'],
};
